import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
page.on("console", (m) => { if (m.type() === "error") console.log("CONSOLE", m.text()); });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.waitForTimeout(800);
await page.getByRole("button", { name: "BẬT GPS THEO DÕI" }).click();
await page.waitForTimeout(2800);
const banner = await page.locator("text=/GNSS|Mô phỏng|GPS/").first().innerText().catch(() => "");
console.log("BANNER", banner);
await page.screenshot({ path: "/workspace/screenshots/tracking-mobile.png" });
await page.getByRole("button", { name: /Satellites/ }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: "/workspace/screenshots/sats-mobile.png" });
await page.getByRole("button", { name: /Speed Chart/ }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/screenshots/chart-mobile.png" });
await page.getByRole("button", { name: /Log/ }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/screenshots/export-mobile.png" });
await page.getByRole("button", { name: /Current Track/ }).click();
await page.getByRole("button", { name: /Bảng thông số/ }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: "/workspace/screenshots/stats-mobile.png" });
const speedText = await page.locator("body").innerText();
console.log("BODY_PREFIX", speedText.slice(0, 400).replace(/\n/g, " | "));
await browser.close();
console.log("QA done");
